name: CI

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - master

env:
  MAVEN_OPTS: -Xmx2g

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          # https://github.com/actions/setup-java#supported-distributions
          distribution: zulu
          cache: maven

      # https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      # https://docs.travis-ci.com/user/languages/java/#maven-default-script-command
      - run: mvn test -B
